spring:
  datasource:
    username: zhangsan
    password: rootroot
    url: jdbc:mysql://192.168.181.128:3306/springboot?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml #指定住配置文件
  mapper-locations: classpath:/mybatis/mapper/*.xml #指定xml映射 文件路径
  type-aliases-package: com.atguigu.domain #指定mybatis包的别名
logging:
  level:
    com.atguigu.dao: debug #配置日志
